name: PR Title Check
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'
      - 'development'
      - 'feat/onboarding-v2'

jobs:
  check_admin:
    name: Check Admin User
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN: pratikshinde590
      OTHER_ADMINS: "anotherAdmin,thirdAdmin"  # Add other admin usernames if needed
    steps:
      - name: Admin Check
        if: ${{ !contains(env.NAME_ADMIN + ',' + env.OTHER_ADMINS, github.actor) }}
        run: exit 1
      - name: Admin Check Passed
        if: ${{ contains(env.NAME_ADMIN + ',' + env.OTHER_ADMINS, github.actor) }}
        run: echo "Admin check passed"
